""" Location of log files """
PUBLIC_LOG_FOLDER = "/data/pub"
ACCESS_LOGS = PUBLIC_LOG_FOLDER + "/accesslogs/aclog.current"
AUTH_LOGS = PUBLIC_LOG_FOLDER + "/authlogs/authlog.current"
AVC_LOGS = PUBLIC_LOG_FOLDER + "/avc_logs/avc_log.current"
BYPASS_LOGS = PUBLIC_LOG_FOLDER + "/bypasslogs/tmon_bypass.current"
CLI_LOGS = PUBLIC_LOG_FOLDER + "/cli_logs/cli.current"
CONFIGDEFRAGD_LOGS = PUBLIC_LOG_FOLDER + \
	"/configdefragd_logs/configdefragd_log.current"
CONFIGURATION = PUBLIC_LOG_FOLDER + "/configuration/config.dtd"
DCA_LOGS = PUBLIC_LOG_FOLDER + "/dca_logs/dca_log.current"
EXTERNAL_AUTH_LOGS = PUBLIC_LOG_FOLDER + \
	"/external_auth_logs/external_auth_logs.current"
FEEDBACK_LOGS = PUBLIC_LOG_FOLDER + "/feedback_logs/feedback_log.current"
FEEDSD_LOGS = PUBLIC_LOG_FOLDER + "/feedsd_logs/feedsd_log.current"
FIPS_LOGS = PUBLIC_LOG_FOLDER + "/fips_logs/fips_logs.current"
FTPD_LOGS = PUBLIC_LOG_FOLDER + "/ftpd_logs/ftpd.current"
GUI_LOGS = PUBLIC_LOG_FOLDER + "/gui_logs/gui.current"
HAYSTACKD_LOGS = PUBLIC_LOG_FOLDER + "/haystackd_logs/haystackd.current"
IDSDATALOSS_LOGS = PUBLIC_LOG_FOLDER + \
	"/idsdataloss_logs/idsdataloss_log.current"
LOGDERROR_LOGS = PUBLIC_LOG_FOLDER + "/logderrorlogs/logderrlog.current"
MCAFEE_LOGS = PUBLIC_LOG_FOLDER + "/mcafee_logs/mcafee_log.current"
MUSD_LOGS = PUBLIC_LOG_FOLDER + "/musd_logs/musd_log.current"
PACD_LOGS = PUBLIC_LOG_FOLDER + "/pacd_logs/pacd_log.current"
PROXY_LOGS = PUBLIC_LOG_FOLDER + "/proxylogs/proxyerrlog.current"
REPORTD_LOGS = PUBLIC_LOG_FOLDER + "/reportd_logs/reportd.current"
REPORTING = PUBLIC_LOG_FOLDER + "/reporting/incoming_queue"
REPORTQUERYD_LOGS = PUBLIC_LOG_FOLDER + \
	"/reportqueryd_logs/reportqueryd.current"
SAAS_AUTH_LOGS = PUBLIC_LOG_FOLDER + "/saas_auth_log/saas_auth_log.current"
SHD_LOGS = PUBLIC_LOG_FOLDER + "/shd_logs/shd.current"
SNTPD_LOGS = PUBLIC_LOG_FOLDER + "/sntpd_logs/sntpd.current"
SOPHOS_LOGS = PUBLIC_LOG_FOLDER + "/sophos_logs/sophos_log.current"
STATUS = PUBLIC_LOG_FOLDER + "/status/status.log.current"
SYSTEM_LOGS = PUBLIC_LOG_FOLDER + "/system.current"
TRACK_STATS = PUBLIC_LOG_FOLDER + "/track_stats/prox_track.log"
TRAFMON_ERR_LOGS = PUBLIC_LOG_FOLDER + "/trafmon_errlogs/tmon_err.current"
TRAFMON_LOGS = PUBLIC_LOG_FOLDER + "/trafmonlogs/tmon_misc.current"
UDS_LOGS = PUBLIC_LOG_FOLDER + "/uds_logs/uds_log.current"
IPDATER_LOGS = PUBLIC_LOG_FOLDER + "/updater_logs/updater_log.current"
WBNP_LOGS = PUBLIC_LOG_FOLDER + "/wbnp_logs/wbnp_log.current"
WEBROOT_LOGS = PUBLIC_LOG_FOLDER + "/webrootlogs/webrootlog.current"
WELCOMEACK_LOGS = PUBLIC_LOG_FOLDER + "/welcomeack_logs/welcomeack_log.current"

